name: Python application
on:
  push:
    branches: 
      - master
        - code_structure

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        pip install pylint
    - name: Lint with pycodestyle - will fail and stop on any issues!
      run: |
        pycodestyle cleandata*.py
    - name: pylint on code directory. N.B. always passes! Please check log below for issues.
      run: |
        pylint --exit-zero -d logging-fstring-interpolation,logging-format-interpolation cleandata*.py
